// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfCo6ZP0Tz3K_EWaRLyCWln3FSquOhmtE',
    appId: '1:932371770024:web:0054ea3b41e9babeeb709d',
    messagingSenderId: '932371770024',
    projectId: 'quizapp-3fd05',
    authDomain: 'quizapp-3fd05.firebaseapp.com',
    storageBucket: 'quizapp-3fd05.firebasestorage.app',
    measurementId: 'G-3NVQ3PCF30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvTsGNeE5Egp1g6vg47LhPrTMFp3GctCA',
    appId: '1:932371770024:android:8b3a11d3ead9211beb709d',
    messagingSenderId: '932371770024',
    projectId: 'quizapp-3fd05',
    storageBucket: 'quizapp-3fd05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv5RqeBiLZnCJ7karWcv4kr5DfNQWnqMw',
    appId: '1:932371770024:ios:5eb462222fb4adc8eb709d',
    messagingSenderId: '932371770024',
    projectId: 'quizapp-3fd05',
    storageBucket: 'quizapp-3fd05.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );
}
